# Introduction à numpy
Pour stocker des valeurs numeriques on se sert de la librarie numpy. Elle permet un calcul très efficace et rapide en utilisant des vecteurs et matrices. On utilise la convention

In [1]:
import numpy as np

In [2]:
new_array = np.array([1, 2, 3, 4])
print(new_array)

[1 2 3 4]


Exercise: créer le vecteur qui contient [0, 5, 8, 10] et qui s'appelle a

Maintenant on va gener des valeurs alléatoires pour jouer avec

In [3]:
dim, N_samples = 4, 20

In [4]:
np.random.seed(42) # pour s'assurer qu'on obient tous les meme valeurs !
random_noise = np.random.randn(N_samples, dim) # a quoi correspond ça ?  

In [5]:
random_noise.shape

(20, 4)

In [6]:
# choisir la premiere ligne:
print random_noise[0,:]

# choisir la pemiere cologne
print random_noise[:,0]

# choisir la valeur a la position 1, 1
print random_noise[1,1]
# choisir la derniere valeur
print random_noise[-1, -1]

# et on peut aussi choisir une plage de valeure:
print random_noise[1:10, -1] # ca fait qoui exactement ??

[ 0.49671415 -0.1382643   0.64768854  1.52302986]
[ 0.49671415 -0.23415337 -0.46947439  0.24196227 -1.01283112  1.46564877
 -0.54438272 -0.60063869 -0.01349722  0.2088636   0.73846658 -1.47852199
  0.34361829 -0.676922   -0.83921752 -0.47917424  0.81252582  0.36163603
 -0.03582604  0.08704707]
-0.23413695694918055
-1.9875689146008928
[ 0.76743473 -0.46572975 -0.56228753 -1.4123037  -1.42474819  0.37569802
  1.85227818 -1.22084365  0.19686124]


Ajouter le vecteur [1,2,3,4] a chaque ligne

In [7]:
to_add = np.array([1,2,3,4])
random_noise + to_add # numpy comprend tout seul ! 

array([[ 1.49671415,  1.8617357 ,  3.64768854,  5.52302986],
       [ 0.76584663,  1.76586304,  4.57921282,  4.76743473],
       [ 0.53052561,  2.54256004,  2.53658231,  3.53427025],
       [ 1.24196227,  0.08671976,  1.27508217,  3.43771247],
       [-0.01283112,  2.31424733,  2.09197592,  2.5876963 ],
       [ 2.46564877,  1.7742237 ,  3.0675282 ,  2.57525181],
       [ 0.45561728,  2.11092259,  1.84900642,  4.37569802],
       [ 0.39936131,  1.70830625,  2.39829339,  5.85227818],
       [ 0.98650278,  0.94228907,  3.82254491,  2.77915635],
       [ 1.2088636 ,  0.04032988,  1.67181395,  4.19686124],
       [ 1.73846658,  2.17136828,  2.88435172,  3.6988963 ],
       [-0.47852199,  1.28015579,  2.53936123,  5.05712223],
       [ 1.34361829,  0.23695984,  3.32408397,  3.61491772],
       [ 0.323078  ,  2.61167629,  4.03099952,  4.93128012],
       [ 0.16078248,  1.69078762,  3.33126343,  4.97554513],
       [ 0.52082576,  1.81434102,  1.89366503,  2.80379338],
       [ 1.81252582,  3.

Par contre

In [8]:
random_noise + to_add[:,np.newaxis] # attention au taille ! pour ajouter une nouvelle axes

ValueError: operands could not be broadcast together with shapes (20,4) (4,1) 

ce qui marche aussi: 

In [9]:
random_noise + 2
random_noise/ 2

array([[ 0.24835708, -0.06913215,  0.32384427,  0.76151493],
       [-0.11707669, -0.11706848,  0.78960641,  0.38371736],
       [-0.23473719,  0.27128002, -0.23170885, -0.23286488],
       [ 0.12098114, -0.95664012, -0.86245892, -0.28114376],
       [-0.50641556,  0.15712367, -0.45401204, -0.70615185],
       [ 0.73282438, -0.11288815,  0.0337641 , -0.71237409],
       [-0.27219136,  0.05546129, -0.57549679,  0.18784901],
       [-0.30031934, -0.14584687, -0.30085331,  0.92613909],
       [-0.00674861, -0.52885546,  0.41127246, -0.61042182],
       [ 0.1044318 , -0.97983506, -0.66409302,  0.09843062],
       [ 0.36923329,  0.08568414, -0.05782414, -0.15055185],
       [-0.739261  , -0.3599221 , -0.23031939,  0.52856111],
       [ 0.17180914, -0.88152008,  0.16204198, -0.19254114],
       [-0.338461  ,  0.30583814,  0.51549976,  0.46564006],
       [-0.41960876, -0.15460619,  0.16563172,  0.48777256],
       [-0.23958712, -0.09282949, -0.55316749, -0.59810331],
       [ 0.40626291,  0.

On peut d'algebre: 
on calculera $X'X$, on calculera $(X'X)^{-1}$ avec random_noise et $X'X (X'X)^{-1}$

In [10]:
X = random_noise
X_prod = X.transpose().dot(X)
X_prod_inv = np.linalg.inv(X.transpose().dot(X))
X_prod.dot(X_prod_inv) # la difference vient des erreures numeriques


array([[ 1.00000000e+00, -6.34422226e-19, -4.18746126e-19,
         1.16927108e-17],
       [-1.51450875e-18,  1.00000000e+00,  2.70755309e-18,
        -1.61842194e-17],
       [-7.08928072e-19,  3.21336902e-18,  1.00000000e+00,
         1.42141654e-17],
       [ 1.55949302e-17,  3.17779309e-17, -5.07100510e-19,
         1.00000000e+00]])

Des fonctionnalité très utilies : 

In [11]:
print X.mean(axis=0) 
# mais
print X.mean() 
# et 
print X.mean(axis=1) 
print X.var(axis=0)
print X.sum(axis=0)

[-0.08140784 -0.25353786 -0.26475727  0.10434236]
-0.1238401516304394
[ 0.63229206  0.4695893  -0.21401545 -0.98963083 -0.75472789 -0.02933688
 -0.30218892  0.08955978 -0.36737672 -0.72053284  0.12327072 -0.40047069
 -0.37010504  0.47425848  0.03959466 -0.7418437   0.77507216  0.40398711
 -0.06725625 -0.52694211]
[0.46821147 0.84513301 0.96963441 1.24773181]
[-1.62815674 -5.07075721 -5.29514532  2.08684713]


Que font les fonctions suivantes ? 

In [ ]:
np.ones(10)
np.zeros(10)
np.linspace(0,10)
np.eye(10)

## Exercise: 
Faisons encore un pey d'algebre lineaire : 
On calcule les iterations suivantes
$$
b_{k+1} = \frac{A b_k}{\| A b_k \|},
$$
avec la norme euclidienne. L'iteration converge vers la valeur propres la plus grande de $A$.
On prendra $A = X'X$. 
Solution: https://en.wikipedia.org/wiki/Power_iteration. Ne regardez pas tout de suite !
NB: vous avez besoin de definir un critere d'arret, on utilise une boucle while et on initialize $b_0$ avec un vecteur aléatoire.
